# Generated by Django 4.0.6 on 2022-08-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_noticia', models.CharField(max_length=100)),
                ('content_noticia', models.CharField(max_length=200)),
            ],
        ),
    ]
